module uim.platform.ecm.application.usecases.manage.manage_ecm_objects;

import std.conv : to;
import std.datetime : Clock;
import uim.platform.ecm.application.dto : CommandResult, EcmObjectDTO;
import uim.platform.ecm.domain.entities.ecm_object : EcmObject, BusinessObjectType;
import uim.platform.ecm.domain.repositories.ecm_repository : EcmRepository;
import uim.platform.ecm.domain.services.ecm_validator : EcmValidator;

@safe:

class ManageEcmObjectsUseCase {
    private EcmRepository repository;

    this(EcmRepository repository) {
        this.repository = repository;
    }

    EcmObject[] list(string objectType) {
        return repository.listByType(objectType);
    }

    EcmObject[] listDocumentVersions(string documentId) {
        return repository.listDocumentVersions(documentId);
    }

    const(EcmObject)* get_(string objectType, string id) {
        return repository.getByTypeAndId(objectType, id);
    }

    CommandResult create(EcmObjectDTO dto) {
        EcmObject value = toEntity(dto, true);
        value.id = dto.id.length ? dto.id : createCode(dto.objectType);

        if (!EcmValidator.isValid(value)) {
            return CommandResult(false, "", "objectType and one of name/title are required");
        }

        if (value.objectType == BusinessObjectType.documentVersion && value.parentId.length == 0) {
            return CommandResult(false, "", "Document version requires parentId (document id)");
        }

        if (!repository.create(value)) {
            return CommandResult(false, "", "Object already exists");
        }

        if (value.objectType == BusinessObjectType.document) {
            auto seedVersion = EcmObject(
                createCode(BusinessObjectType.documentVersion),
                BusinessObjectType.documentVersion,
                value.tenantId,
                "1.0",
                "Initial Version",
                "active",
                value.id,
                value.owner,
                "Autogenerated initial version",
                "",
                value.createdBy,
                value.modifiedBy,
                value.createdAt,
                value.modifiedAt,
                ["versionLabel": "1.0"]
            );
            repository.create(seedVersion);
        }

        if (value.objectType != BusinessObjectType.auditEntry) {
            repository.create(newAudit("CREATE", value));
        }

        return CommandResult(true, value.id, "");
    }

    CommandResult update(EcmObjectDTO dto) {
        auto current = repository.getByTypeAndId(dto.objectType, dto.id);
        if (current is null) {
            return CommandResult(false, "", "Object not found");
        }

        EcmObject value = cloneObject(*current);
        if (dto.name.length) value.name = dto.name;
        if (dto.title.length) value.title = dto.title;
        if (dto.status.length) value.status = dto.status;
        if (dto.parentId.length) value.parentId = dto.parentId;
        if (dto.owner.length) value.owner = dto.owner;
        if (dto.description.length) value.description = dto.description;
        if (dto.externalReference.length) value.externalReference = dto.externalReference;
        if (dto.metadata.length) value.metadata = dto.metadata;
        value.modifiedBy = dto.modifiedBy;
        value.modifiedAt = Clock.currTime().toISOExtString();

        if (!repository.update(value)) {
            return CommandResult(false, "", "Object not found");
        }

        if (value.objectType != BusinessObjectType.auditEntry) {
            repository.create(newAudit("UPDATE", value));
        }

        return CommandResult(true, value.id, "");
    }

    CommandResult remove(string objectType, string id) {
        auto current = repository.getByTypeAndId(objectType, id);
        if (current is null) {
            return CommandResult(false, "", "Object not found");
        }

        auto snapshot = cloneObject(*current);

        if (!repository.remove(objectType, id)) {
            return CommandResult(false, "", "Object not found");
        }

        if (objectType != BusinessObjectType.auditEntry) {
            repository.create(newAudit("DELETE", snapshot));
        }

        return CommandResult(true, id, "");
    }

    private EcmObject toEntity(EcmObjectDTO dto, bool isCreate) {
        auto now = Clock.currTime().toISOExtString();
        EcmObject value;
        value.id = dto.id;
        value.objectType = dto.objectType;
        value.tenantId = dto.tenantId;
        value.name = dto.name;
        value.title = dto.title;
        value.status = dto.status.length ? dto.status : "active";
        value.parentId = dto.parentId;
        value.owner = dto.owner;
        value.description = dto.description;
        value.externalReference = dto.externalReference;
        value.createdBy = dto.createdBy;
        value.modifiedBy = dto.modifiedBy;
        value.createdAt = isCreate ? now : "";
        value.modifiedAt = now;
        value.metadata = dto.metadata;
        return value;
    }

    private EcmObject newAudit(string action, EcmObject source) {
        EcmObject audit;
        audit.id = createCode(BusinessObjectType.auditEntry);
        audit.objectType = BusinessObjectType.auditEntry;
        audit.tenantId = source.tenantId;
        audit.name = action;
        audit.title = source.objectType ~ ":" ~ source.id;
        audit.status = "done";
        audit.parentId = source.id;
        audit.owner = source.owner;
        audit.description = source.description;
        audit.externalReference = source.externalReference;
        audit.createdBy = source.modifiedBy.length ? source.modifiedBy : source.createdBy;
        audit.modifiedBy = source.modifiedBy;
        audit.createdAt = Clock.currTime().toISOExtString();
        audit.modifiedAt = audit.createdAt;
        audit.metadata["action"] = action;
        audit.metadata["objectType"] = source.objectType;
        return audit;
    }

    private EcmObject cloneObject(in EcmObject source) {
        EcmObject copy;
        copy.id = source.id;
        copy.objectType = source.objectType;
        copy.tenantId = source.tenantId;
        copy.name = source.name;
        copy.title = source.title;
        copy.status = source.status;
        copy.parentId = source.parentId;
        copy.owner = source.owner;
        copy.description = source.description;
        copy.externalReference = source.externalReference;
        copy.createdBy = source.createdBy;
        copy.modifiedBy = source.modifiedBy;
        copy.createdAt = source.createdAt;
        copy.modifiedAt = source.modifiedAt;
        copy.metadata = source.metadata.dup;
        return copy;
    }

    private string createCode(string objectType) {
        auto prefix = objectType.length ? objectType[0 .. 1] : "X";
        return prefix ~ "-" ~ to!string(Clock.currTime().stdTime);
    }
}

unittest {
    import uim.platform.ecm.infrastructure.persistence.memory.ecm_repository : MemoryEcmRepository;

    auto repo = new MemoryEcmRepository();
    auto useCase = new ManageEcmObjectsUseCase(repo);

    EcmObjectDTO repositoryDto;
    repositoryDto.objectType = BusinessObjectType.repository;
    repositoryDto.name = "Main Repository";
    repositoryDto.createdBy = "tester";

    auto created = useCase.create(repositoryDto);
    assert(created.success);

    auto item = useCase.get_(BusinessObjectType.repository, created.id);
    assert(item !is null);
    assert((*item).name == "Main Repository");

    repositoryDto.id = created.id;
    repositoryDto.modifiedBy = "tester2";
    repositoryDto.description = "Updated";
    auto updated = useCase.update(repositoryDto);
    assert(updated.success);

    auto deleted = useCase.remove(BusinessObjectType.repository, created.id);
    assert(deleted.success);
}
