apiVersion: v1
kind: Service
metadata:
  name: team
  namespace: uim-platform
  labels:
    app: team
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: team
  ports:
  - name: http
    port: 8150
    targetPort: 8150
    protocol: TCP
