apiVersion: v1
kind: ConfigMap
metadata:
  name: product-development-config
  namespace: uim-platform
  labels:
    app: product-development
    part-of: uim-platform
data:
  PRODUCT_DEVELOPMENT_HOST: "0.0.0.0"
  PRODUCT_DEVELOPMENT_PORT: "8106"
