apiVersion: v1
kind: Service
metadata:
  name: product-development
  namespace: uim-platform
  labels:
    app: product-development
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: product-development
  ports:
  - name: http
    port: 8106
    targetPort: 8106
    protocol: TCP
