apiVersion: v1
kind: Service
metadata:
  name: freight-collaboration
  namespace: uim-platform
  labels:
    app: freight-collaboration
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: freight-collaboration
  ports:
  - name: http
    port: 8140
    targetPort: 8140
    protocol: TCP
