apiVersion: v1
kind: Service
metadata:
  name: apm
  namespace: uim-platform
  labels:
    app: apm
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: apm
  ports:
  - name: http
    port: 8140
    targetPort: 8140
    protocol: TCP
