apiVersion: v1
kind: Service
metadata:
  name: mrp
  namespace: uim-platform
  labels:
    app: mrp
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: mrp
  ports:
  - name: http
    port: 8119
    targetPort: 8119
    protocol: TCP
