apiVersion: v1
kind: Service
metadata:
  name: lean
  namespace: uim-platform
  labels:
    app: lean
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: lean
  ports:
  - name: http
    port: 8130
    targetPort: 8130
    protocol: TCP
