apiVersion: v1
kind: Service
metadata:
  name: network-asset-collaboration
  namespace: uim-platform
  labels:
    app: network-asset-collaboration
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: network-asset-collaboration
  ports:
  - name: http
    port: 8104
    targetPort: 8104
    protocol: TCP
