apiVersion: v1
kind: ConfigMap
metadata:
  name: asset-strategy-performance-config
  namespace: uim-platform
  labels:
    app: asset-strategy-performance
    part-of: uim-platform
data:
  ASSET_STRATEGY_PERFORMANCE_HOST: "0.0.0.0"
  ASSET_STRATEGY_PERFORMANCE_PORT: "8105"
