apiVersion: v1
kind: Service
metadata:
  name: ps
  namespace: uim-platform
  labels:
    app: ps
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: ps
  ports:
  - name: http
    port: 8121
    targetPort: 8121
    protocol: TCP
