apiVersion: v1
kind: Service
metadata:
  name: asset-strategy-performance
  namespace: uim-platform
  labels:
    app: asset-strategy-performance
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: asset-strategy-performance
  ports:
  - name: http
    port: 8105
    targetPort: 8105
    protocol: TCP
