apiVersion: v1
kind: Service
metadata:
  name: itil
  namespace: uim-platform
  labels:
    app: itil
    part-of: uim-platform
spec:
  type: ClusterIP
  selector:
    app: itil
  ports:
  - name: http
    port: 8140
    targetPort: 8140
    protocol: TCP
